USE sakila;


#1. List the number of films per category.
SELECT * FROM category;
SELECT * FROM film_category;

SELECT film.film_id, film.title, film_category.category_id, category.category_id, category.name
FROM film
JOIN film_category ON film.film_id = film_category.film_id
JOIN category ON category.category_id = film_category.film_id;

#2. Retrieve the store ID, city, and country for each store.
SELECT * FROM city;
SELECT * FROM store;
SELECT * FROM country;
SELECT * FROM address;

SELECT store.store_id, store.address_id, city.city_id, country.country_id, country.country
FROM store
JOIN address ON address.address_id = store.address_id  -- Use the correct spelling "address"
JOIN city ON city.city_id = address.city_id  -- Join city based on address information
JOIN country ON country.country_id = city.country_id;

#3. Calculate the total revenue generated by each store in dollars
SELECT store.store_id, staff.staff_id, staff.store_id, payment.staff_id, payment.amount
FROM store
JOIN staff ON staff.store_id = store.store_id
JOIN payment ON payment.staff_id = staff.staff_id;

#4 Determine the average running time of films for each category

SELECT category.name, AVG(film.length) AS avg_length
FROM film
JOIN film_category ON film.film_id = film_category.film_id
JOIN category ON category.category_id = film_category.category_id
GROUP BY category.name;

####BONUS####
#5.Identify the film categories with the longest average running time
SELECT category.name, AVG(film.length) AS avg_length
FROM film
JOIN film_category ON film.film_id = film_category.film_id
JOIN category ON category.category_id = film_category.category_id
GROUP BY category.name
ORDER BY avg_length DESC;

#6.Display the top 10 most frequently rented movies in descending order.
SELECT f.title, COUNT(r.rental_id) AS rental_count
FROM rental r
JOIN inventory i ON r.inventory_id = i.inventory_id
JOIN film f ON i.film_id = f.film_id
GROUP BY f.title
ORDER BY rental_count DESC
LIMIT 10;

#7. Determine if "Academy Dinosaur" can be rented from Store 1
SELECT 
    f.title, 
    s.store_id, 
    COUNT(i.inventory_id) AS available_copies
FROM film f
JOIN inventory i ON f.film_id = i.film_id
JOIN store s ON i.store_id = s.store_id
LEFT JOIN rental r ON i.inventory_id = r.inventory_id AND r.return_date IS NULL
WHERE f.title = 'Academy Dinosaur'
  AND s.store_id = 1
  AND r.rental_id IS NULL
GROUP BY f.title, s.store_id;
































